n = int(input('Digite um numero para vermos a sua tabuada: '))

print(f"{'Tabuada':=^20}")
print(f'0  x {n:2} = {n*0}')
print(f'1  x {n:2} = {n*1}')
print(f'2  x {n:2} = {n*2}')
print(f'3  x {n:2} = {n*3}')
print(f'4  x {n:2} = {n*4}')
print(f'5  x {n:2} = {n*5}')
print(f'6  x {n:2} = {n*6}')
print(f'7  x {n:2} = {n*7}')
print(f'8  x {n:2} = {n*8}')
print(f'9  x {n:2} = {n*9}')
print(f"{'Tabuada':=^20}")